export default {
  LOAD_COURSES_SUCCES: 'LAOD_COURSES_SUCCESS',
  LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS'
};
