// export default {
//   LOAD_COURSES_SUCCES: 'LAOD_COURSES_SUCCESS',
//   LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
//   CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
//   UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS'
// };

export const LOAD_COURSES_SUCCES = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_FAILED = 'API_CALL_FAILED';

export const DELETE_COURSE_OPTIMISTIC = 'DELETE_COURSE_OPTIMISTIC';
